### ISSUE TITLE
EJS 2 link not found

### ISSUE THREAD

**Issue by jyotman** [nwoltman/sublime-ejs#1]
The [link](https://packagecontrol.io/packages/EJS 2) provided in the readme to the EJS 2 package is not valid. Also the package can't be found in the package manager

**Comment by nwoltman** [comment]
Wow, I didn't think anyone would find this repo so soon :open_mouth:. I wrote that link in anticipation of this package's release. I'm still waiting for it to be added to package control. You can follow it's status here: wbond/package_control_channel#5462

**Comment by nwoltman** [comment]
EJS 2 is now in package control and the link now works :smiley:
