### ISSUE TITLE
Highlighting Within Delimiters

### ISSUE THREAD

**Issue by sabriele** [nwoltman/sublime-ejs#2]
Hi there, 

First off, this is not really an 'issue'; I would just like to clarify how my code should be highlighted within the `<% %>` delimiters.

When I first installed EJS2 the `.` and the `/` within the delimiters were not highlighted any differently than the rest of the text inside the brackets (all white).

![photo 30-8-16 5 40 28 am](https://cloud.githubusercontent.com/assets/4678102/18092314/71445270-6efe-11e6-8f43-2f8d88dce473.jpg)
_(sorry for the really blurry photo)_

Afterwards, I installed the Babel package, and the resulting syntax highlighting is shown below. I am not, however, 100% sure if the change in highlighting happened as a direct result of installing Babel; I did work on a couple of other things on Sublime Text (not related to EJS) in between installing the two packages.

![screenshot 2016-08-30 06 56 49](https://cloud.githubusercontent.com/assets/4678102/18092347/88998b52-6efe-11e6-8d77-bad3b7e9368a.png)

The highlighting persists even when I use the Dracula EJS theme you suggested, as well as for the other delimiters `<? ?>`, `<$ $>` and `<@ @>`.

I am new to EJS so I apologise in advance for not being sure which of these is the traditionally accepted syntax highlighting.

P.S If it's not too much trouble, I think adding some screenshots/gifs of the expected syntax highlighting before/after installing the package in the ReadMe would be awesome.

Thanks so much! :)

**Comment by nwoltman** [comment]
Hi @sabriele,

I can assure you that the change in the highlighting was certainly a direct result of installing Babel. While it is possible to use the EJS 2 package without Babel, anything between the delimiters will always be highlighted incorrectly if Babel is not installed.

I'll add a screenshot of some example EJS code with everything installed properly to clearly show what it's supposed to look like :)

**Comment by sabriele** [comment]
Thanks so much for the quick reply Nathan! And the added screenshots :)
