### ISSUE TITLE
Add a speach about jsx

### ISSUE THREAD

**Issue by A-312** [nwoltman/sublime-ejs#4]
I [discover accidentally](https://github.com/nwoltman/sublime-ejs/blob/master/JavaScript%20-%20EJS.sublime-syntax#L1157) that this plugin support JSX syntax, I think you should add a speach in the readme about that and maybe support by default `source.jsx` files. :)

**Comment by nwoltman** [comment]
This plugin only supports JSX syntax if it happens to be inside a `<script>` tag in a `.ejs` file. It does not support `.jsx` files. If you open a `.jsx` file using the EJS syntax from this plugin, it will look very different than if you used a proper JavaScript syntax. This plugin uses a direct copy of the [babel-sublime](https://github.com/babel/babel-sublime) syntax, so you could use that plugin if you wanted to, but it's no longer being updated. I'd suggest using the [JS-Custom](https://github.com/Thom1729/Sublime-JS-Custom) plugin. That's what I use for JSX and it works really well.
